# Generated by Django 5.0.6 on 2024-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
